# Generated by Django 4.1.5 on 2023-01-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchobb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
